version: '3'

#---NETWORKS---------------------------------------------------
networks:
  default:
    external:
      name: helixcore_app_net


services:
  helixcore:
    container_name: helix-auth-svc
    image: helix-auth-svc
    build:
      context: ./auth
      dockerfile: Dockerfile
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    privileged: true
    command:
      - /sbin/init
    ports:
      - "3000:3000"